server:
  port: 9902

spring:
  dataSource:
    username: root
    password: yyn990902
    url: jdbc:mysql:///yzynDataBase
  redis:
    port: 6379
    host: localhost
    password: 123456

mybatis-plus:
  mapper-locations: classpath:com/yzyn/sys/mapper/*.xml

logging:
  level:
    com.yzyn: debug
